Repository LuizLimaDev/front-back-mountain-frontend, pull requests merged in 2023-09, with the labels that each got.

#20 Correções na página de login e produção do modal de clientes
  src/assets/closeIcon.svg
  src/assets/users.svg
  src/components/ClientModal/index.jsx
  src/context/SingContext.jsx
  src/pages/SingUp/Password/index.jsx
  src/pages/SingUp/SingUp.jsx
  src/styles/muiTheme.jsx
Labels: bug, create

#21 Feature/dashboard
  src/assets/chevron-down.png
  src/components/billing-detailed/billing-detailed-overdue/index.jsx
  src/components/billing-detailed/billing-detailed-overdue/style.css
  src/components/billing-detailed/billing-detailed-paid/index.jsx
  src/components/billing-detailed/billing-detailed-paid/style.css
  src/components/billing-value/billing-value-overdue/index.jsx
  src/components/billing-value/billing-value-overdue/style.css
  src/components/billing-value/billing-value-paid/index.jsx
  src/components/billing-value/billing-value-paid/style.css
  src/components/clients/clients-nonpaying/index.jsx
  src/components/clients/clients-nonpaying/style.css
  src/components/clients/clients-paying/style.css
  src/components/header/index.jsx
  src/components/header/style.css
  src/pages/Home/Home.jsx
  src/pages/Home/styles.css
Labels: create

#28 Feature/integracao com front end metricas
  src/components/billing-detailed/billing-detailed-overdue/index.jsx
  src/components/billing-detailed/billing-detailed-paid/index.jsx
  src/components/billing-detailed/billing-detailed-projected/index.jsx
  src/components/billing-value/billing-value-overdue/index.jsx
  src/components/billing-value/billing-value-paid/index.jsx
  src/components/billing-value/billing-value-projected/index.jsx
  src/components/clients/clients-nonpaying/index.jsx
  src/components/clients/clients-paying/index.jsx
  src/context/MetricsDashboard.jsx
  src/hooks/useMetricsDashboard.jsx
  src/pages/Home/Home.jsx
Labels: bug, create

#60 Bugfix/voltarclickdostepper
  src/components/RegisterLayout/index.jsx
Labels: create

#89 Bugfix/bug de modal de charges
  src/assets/Menu/billings_active.svg
  src/components/HeaderDashBoard/ClientBreadcrumbs/ClientBreadcrumbs.jsx
  src/components/HeaderDashBoard/index.jsx
  src/components/Modals/ChargeModal/index.jsx
  src/components/menu-icon/index.jsx
  src/components/page-clients/clients-table/index.jsx
  src/context/CustomersContext.jsx
  src/hooks/useCustomers.jsx
  src/pages/ClientDetailed/ClientDetailed.jsx
  src/styles/muiTheme.jsx
Labels: bug, create

#105 fix: arrumar rotas protegidas
  src/routes/routes.jsx
Labels: bug

#111 Bugfix/atualizar lista de clientes
  src/components/ClientModal/index.jsx
Labels: bug

#133 feat: criar modal de edit cobrancas e fazer funcionalidade
  src/components/DataDisplay/Tables/Billings-table/index.jsx
  src/components/Layouts/HomeLayout/index.jsx
  src/components/Utils/Modals/EditChargeModal/EditChargeModal.jsx
  src/context/ChargesContext.jsx
  src/context/ModalsContext.jsx
  src/hooks/useCharges.jsx
  src/pages/Billings/index.jsx
  src/pages/ClientDetailed/index.jsx
Labels: create

#132 Feature/search client
  src/assets/errorPerson.svg
  src/assets/errorSearch.svg
  src/assets/errorX.svg
  src/components/DataDisplay/Tables/Billings-table/index.jsx
  src/components/DataDisplay/Tables/Clients-table/index.jsx
  src/components/Inputs/billings-search/index.jsx
  src/components/Inputs/clients-search/index.jsx
  src/components/Layouts/ErrorSearch/index.jsx
  src/context/ChargesContext.jsx
  src/context/CustomersContext.jsx
  src/context/ModalsContext.jsx
  src/hooks/useCharges.jsx
  src/hooks/useCustomers.jsx
Labels: create
